## Default
# [aws]
# style = "bold #ffb86c"
#
# [character]
# error_symbol = "[位](bold #ff5555)"
# success_symbol = "[位](bold #50fa7b)"
#
# [cmd_duration]
# style = "bold #f1fa8c"
#
# [directory]
# style = "bold #50fa7b"
#
# [git_branch]
# style = "bold #ff79c6"
#
# [git_status]
# style = "bold #ff5555"
#
# [hostname]
# style = "bold #bd93f9"
# ssh_only = false
# detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
# disabled = false
#
# [username]
# format = "[$user]($style) | "
# style_user = "bold #8be9fd"
# style_root = "bold #ff5555"
# show_always = true

## kanagawa
[aws]
style = "bold #DCD7BA" # normal

[character]
error_symbol = "[位](bold #C34043)" # red
success_symbol = "[位](bold #76946A)" # green

[cmd_duration]
style = "bold #C0A36E" # yellow

[directory]
style = "bold #76946A" # green

[git_branch]
style = "bold #957FB8" # magenta

[git_status]
style = "bold #C34043" # red

[hostname]
style = "bold #D27E99" # brmagenta
ssh_only = false
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[username]
format = "[$user]($style) | "
style_user = "bold #7AA89F" # cyan
style_root = "bold #C34043" # red
show_always = true

